### ISSUE TITLE
Asset::add doesn't appear to work

### ISSUE THREAD

**Issue by lougreenwood** [themosis/themosis#101]
Hello :),

I'm trying to figure out how to get asset::add to work - I'm including it in various places around my project (controllers, views, admin?application.php etc), but it never adds the tags to the rendered output.

However, when I var_dump() the output of asset add, I see it constructs the correct asset path, so something is working correctly.

I have a feeling that asset only works if I'm using the scout templates or Wordpress loop or something, however instead I'm using LightnCandy (https://github.com/zordius/lightncandy - a handlebars.js PHP compiler) to compile and output my views - is there some extra step I need to take to get it working?

Any ideas?

Thanks!

**Comment by jlambe** [comment]
Normally you call the class within any files inside the `admin` folder. Assets can also be registered on a per route basis so it means you can call `Asset::add` inside a route closure or the controller method. It works as well inside view composers.

I do not know LightNCandy but assets need the calls to `wp_head()` and `wp_footer()` functions inside your view otherwise they won't be loaded.

**Comment by lougreenwood** [comment]
Thanks, I think wp_head() & wp_footer() are what I need. 👍
