### ISSUE TITLE
routes with get parameters

### ISSUE THREAD

**Issue by red111** [themosis/themosis#106]
Not sure if this is the right place for this questions...

I am trying to create custom routes for our search page, like:

http://mysite.local/my-search-slug/?s=keywords

We have a page with the slug 'my-search-slug' and we defined a route for it:

`Route::any('page', ['my-search-slug', 'uses' => 'PageController@search']);`

It works fine if we go to: 

http://mysite.local/my-search-slug/

But it fails (404) if we add the parameter ?s=xxx

Do we have to define a different route for this page if we plan to add the `s` parameter?

**Comment by jlambe** [comment]
Because the way WordPress handles URLs by default, you first need to register your query parameter so WordPress knows about it.

Use the `add_rewrite_tag` function to tell WordPress what your query var is and add a rewrite rule using the `add_rewrite_rule` function so WordPress knows about your "special" page route.

Check the Rewrite API: https://codex.wordpress.org/Rewrite_API

Once this is done, your existing route should work as well. But perhaps you'll need to use another var name than "s" because it's a reserved term by WordPress (in case of a conflict).
