### ISSUE TITLE
How to route > controller > view

### ISSUE THREAD

**Issue by aa6my** [themosis/themosis#114]
its shows No route defined for this request...

**Comment by Hyra** [comment]
Did you look at http://framework.themosis.com/docs/routing and http://framework.themosis.com/docs/controllers/ ?

Without any sample code it's hard to see where things go haywire ..

**Comment by jlambe** [comment]
Can you post some code?

Otherwise, do not forget it's WordPress way of routing... Meaning that from version 1.2.3, the following code:
```php
Route::get('page', ['contact', 'uses' => 'MyController@contact']);
```
is listening to requests made on `http://mydomain.com/contact/` only if a WordPress page with a slug of `contact` has been created. Otherwise you'll keep having the message no route defined...
