### ISSUE TITLE
Validation: Image Size

### ISSUE THREAD

**Issue by heikobihlmaier** [themosis/themosis#115]
Good Morning.

I have a custom metabox with a image field. 

For this image field I have a custom image size. The user should only choose this image size when he fill in this field.

Can I validate this ? Or I have the possibility to change the selectable image formats ?

Greetings.

**Comment by heikobihlmaier** [comment]
No Idea ?

**Comment by jlambe** [comment]
Hi @heikobihlmaier ,

the media field only register the attachment ID so you can retrieve any image size (registered) you want from WordPress. The best workflow is to use the [wp_get_attachment_image_src](https://developer.wordpress.org/reference/functions/wp_get_attachment_image_src/). You'll be able to define the size you want to retrieve so you don't  have to think about validation regarding the size which is simpler for the user.

Otherwise if you still want to let the user choose an image size, ... you'll need to create your own image field or perhaps add a second select field where the user can choose one pre-registered size for his image?
