### ISSUE TITLE
[1.3] Metabox callback

### ISSUE THREAD

**Issue by bgatellier** [themosis/themosis#155]
Hi @jlambe ,

Is there any way to add operations to the WP [add_meta_box](https://developer.wordpress.org/reference/functions/add_meta_box/) callback using the Metabox Themosis object ?
I saw in themosis-framework/src/Themosis/Metabox/MetaboxBuilder.php that the callback is automatically set, but I'm not able to find if (and where) I can add my operations.

FYI, I'm trying to define a hierarchical link between 2 Custom Post Types, as explained on this article: [Parent Post From Another Post Type And A New URL Structure In WordPress](https://1fix.io/blog/2016/02/05/parent-from-another-cpt/).

Thanks for your job about turning WP in an MVC developer-centric tools ;-)

**Comment by jlambe** [comment]
@bgatellier What you're looking after is a metabox custom view. Simply create a view containing your example code (dropdown list): http://framework.themosis.com/docs/1.3/metabox/#customize-the-metabox

Your view will receive `$__post`, `$__fields` and `$__metabox` variables. In regards to your example, I would also suggest to use a `View::composer()` in order to handle the logic into your own class and pass your metabox view the necessary vars instead of writing php logic inside your metabox custom view.

Hope this helps,

**Comment by bgatellier** [comment]
Thx for your quick reply.

I did not do the matching between the callable function from the WP code reference and the Themosis Metabox custom view.

I'll try that and update the issue if necessary.

**Comment by bgatellier** [comment]
Everything works as expected using the View:composer().

Thx !
