### ISSUE TITLE
Working with SEOPress and generated sitemap

### ISSUE THREAD

**Issue by romainhe** [themosis/themosis#186]
Hi, I've a problem with a wordpress plugin,

The module create some custom actions : (Rewrite rules, vars and conditions to display sitemap)

`add_action( 'init', 'seopress_xml_sitemap_rewrite' );
 add_action( 'query_vars', 'seopress_xml_sitemap_query_vars' );
 add_action( 'template_include', 'seopress_xml_sitemap_change_template', 99999 );`

Conditions works, but the problem is wordpress (or themosis ?) load the "normal" website too and we got the classic `"Cannot modify header information"` error...

Any idea to fix this..? 

![capture](https://user-images.githubusercontent.com/1837829/30854557-58ba7aac-a2b2-11e7-8a56-dbdd45b561db.JPG)

(the [1] block you can see in this picture is a part of the front website loaded with the error handle...)
![image](https://user-images.githubusercontent.com/1837829/30854619-80957aea-a2b2-11e7-8543-8b021e3d52ce.png)

Thx a lot for help !

**Comment by jlambe** [comment]
For what I see I would say that that some output is triggered too early due to one of these hooks. You should probably check the code attached to the `template_include` hook.

You see the error because the local development of the framework do not tolerates PHP Warnings. If you disable error reporting, it should work as "expected" but not recommended.

The file `wp-seopress/inc/functions/sitemap/template-xml-sitemaps.php` is the issue. For me, you should report to the plugin author and let him/her know that its code is called too early in the process.

**Comment by romainhe** [comment]
@jlambe hi, I see the plugin working fine when no routes are set in themosis, do you have any idea with that..? Overide something etc.

Does any themosis routes condition can let wordpress works "by default" ?

thx

**Comment by jlambe** [comment]
Routes are hooked with the `template_redirect` action. But there is no code that modifies the default WordPress behavior. We don't remove/unset any vars or change anything during the process.
