### ISSUE TITLE
Loading Assets using a view composer when using folders

### ISSUE THREAD

**Issue by AMO-MGTSYS** [themosis/themosis#190]
When using the code below in a plugin:
View::composer('folder.subfolder1.subfolder2.home', function () {
    Asset::add('my-handle', 'js/myscript.js', false, '1.0.0', true);
});

Themosis is looking for an asset directory under subfolder2 and not the default dist under plugin root folder.

I'm i missing something?

**Comment by jlambe** [comment]
It is looking for assets in all `dist` directories registered from plugins and the theme. What error message do you receive when calling this code? Normally you should get a not found asset error.

**Comment by AMO-MGTSYS** [comment]
Indeed. I receive a 404 and inspected the linked provided.
I think it has something to do with my plugin structure.

admin
--foder
----file.php (code interacting with themosis facade)
plugin.php

Asset::add('apps-vue', 'js/vue.js' Works when i call  from plugin.php. It doesn't whe i call it from file.php inside
View::composer('folder.subfolder1.subfolder2.home', function () {
Asset::add('apps-vue', 'js/vue.js', false, '1.0.0', false)->to('admin');
});

**Comment by jlambe** [comment]
You should take a look to the plugin boilerplate and start your plugin development with it instead of building your own structure:
- https://framework.themosis.com/docs/1.3/plugin/

Regarding the asset, it might too late to register your asset from a View composer as the headers are sent and a partial view is also rendered. This asset is simply not loaded, especially if it defined to be attached in the `<head>`.
