### ISSUE TITLE
OT: Blog Entry

### ISSUE THREAD

**Issue by devtroll** [themosis/themosis#191]
Good Morning,

I need to create a blog entry about your framework. I want to use your graphic from your homepage on https://framework.themosis.com/. 

Can I use this, when I link to your page?

Another question: Can u say me, what is your reason why you create themosis framework? I want to use this for a quote in the blog entry!

Thanks for answering!

**Comment by jlambe** [comment]
Hello @devtroll.

Yes you can grab the graphic on the home page.

As for why I've created the framework:

The main reason behind the project is to provide a common structure to WordPress application development. The framework provides tools and shortcuts in order to push the limits of what can be built with WordPress.

From that, teams get an application stack they can easily collaborate on, iterate over and easily manage in order to create custom applications with WordPress.

If you need more information regarding your article, don't hesitate to ask!
Where and when is the article going to be published?

Cheers

**Comment by devtroll** [comment]
Hello @jlambe ,

my article is published on our agency website on http://blog.scw.info (german language).

Currently the blog entry is in draft mode, because I work on it. After that I need to wait for the review. I hope, the article is online this week. 

Do you speak german for reading the article in draft mode?

**Comment by jlambe** [comment]
I only have a basic knowledge of german. Just send me the link when it's published and I'll check it. Thanks

**Comment by devtroll** [comment]
Hey Julian,

I will send you the link when It is published.
