### ISSUE TITLE
Using a WP plugin's templates inside Themosis

### ISSUE THREAD

**Issue by lerouxsteyn** [themosis/themosis#230]
Hi there,

Firstly, we love using Themosis, we've used this almost exclusively now for about 2-3 years. Thank you!

There is something I'm missing with regards to WP plugins. For example, a client wants us to develop a site that uses the LearnDash LMS plugin. How would I actually render the templates that are already included in the plugin, or would those not be compatible with Themosis? Is there some way to call or include those templates from Blade plugins? How would the routing work? And apart from wp_head() and wp_footer(), are there any other template tags like that which I need to include in order to give the plugin a place to inject code to?

Any links to relevant documentation would be appreciated as well. 

Thanks.

**Comment by jlambe** [comment]
Hi @lerouxsteyn, by default your plugin should be compatible with the overall Themosis stack.

I'm not sure how the LMS plugin is working against the templates. By default, WordPress has no mechanism to override a theme template from a plugin. Each plugin vendor creates its own way to override those templates. The example that I have in mind for example is WooCommerce, that looks if a sub-folder as been created on your theme with some specific file names. If the file exists, it uses the one from your theme otherwise, it takes the one from the plugin which might call default expected templates files from a WordPress theme (the header.php and footer.php files for example).

Because those files provided by the plugin call suposedly existing theme files which does not exist on a default Themosis theme, you're going to have some errors thrown.

My recommendation for this case could be to write your own theme following some default WordPress standards and from those files, use the View class API to call and render specific blade views for your project.

You can for example, create a `page.php` file at the root of the theme. This file will be used for any WordPress pages. And inside it call the following code:

```php
<?php
echo View::make('pages');
```

Before going further, perhaps it would be best for you to first analyse how your LMS plugin is using the templates coming with it. You'll probably get more hints on how to use them.

**Comment by lerouxsteyn** [comment]
Hi J,

Thanks so much for your reply. That did answer my question.

Thanks again for staying so actively involved in this project.
