### ISSUE TITLE
Want to add new plugin but throw an error "Undefined property: stdClass::$plugin"

### ISSUE THREAD

**Issue by FlickTheManual** [themosis/themosis#254]
Hi everybody,

first of all, nice framework, huge thanks for this pretty and awesome library!

I've got an strange error while I want to add a new plugin from the `Add New` wordpress admin.

I've already deactivate all my plugin, and see what change with a standard theme, and themosis theme, it set the same error.

I've intall themosis from the installation guide ;)

System configuration:

- server : nginx 1.14.1
- PHP : 7.2
- Themosis Framework : 1.3.3
- Wordpress Inner: 4.9.9 (wait for the stable release of the V2 themosis in order to update it to V5)
- Composer up to date from now

screenshot :

![image](https://user-images.githubusercontent.com/2384206/52695077-00acef00-2f85-11e9-8b13-b44da38f995a.png)

Can you help me? Thanks.

**Comment by jlambe** [comment]
Apparently the framework has raised an exception due to a WordPress core issue. You can either deactivate error reporting during development by changing the value of the `THEMOSIS_ERROR` constant to `false` inside your `config/environments/local.php` file or instead of using the GUI for adding new plugins, you could install them though composer using [WPackagist](https://wpackagist.org/) so you don't met the WordPress bug.

**Comment by FlickTheManual** [comment]
thank you so much @jlambe , the wpackagist solution work nicely!

**Comment by jlambe** [comment]
Glad it is solved.
