### ISSUE TITLE
How to implement Blade-SVG

### ISSUE THREAD

**Issue by palicko** [themosis/themosis#284]
Hey,
how can I implement [Blade-SVG](https://github.com/adamwathan/blade-svg) library to Themosis so I'll be able to use it within the theme?

Thanks.

**Comment by jlambe** [comment]
Hi @palicko, apparently nothing special, just follow the installation documentation. Install from the root of your application and instead of using `php artisan` use `php console` to publish the configuration file. You probably also need to register their service provider inside your `config/app.php` file into the `providers` property.

**Comment by VlooMan** [comment]
This is indeed help. Had the same problem and adding `BladeSvg\BladeSvgServiceProvider::class,` to `config/app.php` helped resolve the problem. THANKS!!!
