### ISSUE TITLE
routing wordpress template

### ISSUE THREAD

**Issue by spagi** [themosis/themosis#300]
When I am using wordpress template,themosis routing doesn't work. Always get 404 not found. Any ideas how to handle with this?
Thx.

**Comment by jlambe** [comment]
Hello, could you provide the version framework you're working with, details about your development environment (homestead?) and your code so we can get a better picture of your issue ?

**Comment by spagi** [comment]
Hi, I am using Themosis 2.0, 
wp template: https://themeforest.net/item/jarvis-onepage-parallax-wordpress-theme/5370691
enviroment: docker, image : webdevops/php-apache-dev:7.2

routes/web.php

```
Route::post('/registration','RegistrationController@save')->name('register');

```
`localhost/registration` returns 404

**Comment by Jaspervv** [comment]
Are you sure you're performing a `POST` request to `/registration` since you're registering the route as one?
I've tried recreating it and had no issues. Of course I didn't try it with the theme you're using:  
![code_example](https://user-images.githubusercontent.com/35364310/58464557-32ae1f80-8136-11e9-92c9-bd516a26c925.png)

**Comment by jlambe** [comment]
@spagi Because you're using a default WordPress theme, you can't use routes. If you want to take advantage of the framework, you must convert your theme to a Themosis theme. I would say to move the templates of your theme inside views and move all assets.

**Comment by spagi** [comment]
@jlambe thx
