### ISSUE TITLE
Woocommerce add to cart button

### ISSUE THREAD

**Issue by zecka** [themosis/themosis#303]
Hello, 

I try to use themosis (v2) with woocommerce.

I follow the instructions for installation and everythings work well.

But on the single product page if i click on "add to cart" button this error is displaying:

"The page has expired due to inactivity. "

Any idea why ?

**Comment by jlambe** [comment]
Hello,

this is due to the `VerifyCsrfToken` middleware. You can remove it from your list of active middlewares in the `app/Http/Kernel.php` class, under the `web` group. The middleware is looking after a `_token` parameter on posts requests, if not found, you get a `409` response.

I suggest to deactivate the middleware but if you need it for some specific routes, you can attach it using the `middleware` method on a route.

```php
Route::middleware('csrf')->post('contact-us', function () {
    // code here...
});
```

**Comment by zecka** [comment]
Thank's a lot, it's working now !
