### ISSUE TITLE
wp_mail fails - SMTP Error: Relaying denied 

### ISSUE THREAD

**Issue by vasikgreif** [themosis/themosis#322]
Do I have to do anything special to make `wp_mail` work? When I try to send a message, I get:

`SMTP Error: The following recipients failed: myemail@gmail.com: Relaying denied`

Thanks!

**Comment by jlambe** [comment]
@vasikgreif Unfortunately, there is no longer support here on the repository. We only discuss framework code issue.

For help you can ask inside our [Gitter chat channel](https://gitter.im/themosis/framework) or subscribe to our [enterprise support](https://support.themosis.com) platform.

**Comment by vasikgreif** [comment]
@jlambe Hello, this is not really a support question. I'm pretty sure that `wp_mail` should work out of the box in the framework.

**Comment by KeironLowe** [comment]
@vasikgreif I know this is a bit late, but I just had the same issue and it's due to the `phpmailer_init` action in `App\Hooks\Mail.php`.

It appears that even if your mail driver is set to sendmail, it still tries to use STMP due to that action. Deleting it fixes the issue.

@jlambe should that action be wrapped in a conditional to ensure it's only executed if the driver uses SMTP?

**Comment by theia-kevin** [comment]
> @vasikgreif I know this is a bit late, but I just had the same issue and it's due to the `phpmailer_init` action in `App\Hooks\Mail.php`.
> 
> It appears that even if your mail driver is set to sendmail, it still tries to use SMTP due to that action. Deleting it fixes the issue.
> 
> @jlambe should that action be wrapped in a conditional to ensure it's only executed if the driver uses SMTP?

Thankyou.

For those who are having problems with **wp_mail** on **localhost**, comment out **App\Hooks\Mail::class** on **config/app.php**
