### ISSUE TITLE
domain.tld/cms/wp-admin redirects me to homepage

### ISSUE THREAD

**Issue by johnnypea** [themosis/themosis#38]
I can't enter the wp-admin because it always redirects me to website homepage.

**Comment by jlambe** [comment]
It's a "security" feature. If you want to access the wp-admin, visit the login url:

- Type the full url to login screen (because if you're logged in, it works as expected): `cms/wp-login.php`

You can also restrict access to wp-admin per role using the `application.config.php` file. Remove the roles that can't access the wp-admin from the `access` property.

Also, if you enabled the permalinks, you can access the login screen by using this url: `domain.com/login` (if no published pages).

**Comment by johnnypea** [comment]
Oh, nice! :+1:

**Comment by bactisme** [comment]
I think this should be better explained in configuration !
