### ISSUE TITLE
Creating a Child Theme

### ISSUE THREAD

**Issue by davidgeilfus** [themosis/themosis#39]
Hi,

I’ve created a child theme with this style.css file (as explained [here](http://codex.wordpress.org/Child_Themes)):

    /*
    Theme Name: My child theme
    Theme URI: http://www.mychildtheme.com/
    Template: myparentthemedirectory
    …
    */

I tried to override some files in the app/assets and app/views directories by copying them into the child theme, but they’re ignored. I guess it’s due to the fact that `$paths['base']`, `$paths['app']`, `$paths['admin']` and `$paths['storage']` defined in `themosis_setApplicationPaths()` always point to the parent theme folder?

Could you indicate me the best way to create child themes which inherit most of the features, views, and assets of their parent, while overriding some of them?

Thank you in advance! Best regards

**Comment by jlambe** [comment]
Hi,

first thing to know is that the framework is aimed to custom development. I haven't tested it with parent/child theme but perhaps this might help.

Regarding the `$paths` array, you don't need to modify it. This will keep the parent paths correct if needed. But you probably want to define child theme paths and uris for your views and assets.

Define a view path for your child theme:
```php
// functions.php
/*----------------------------------------------------*/
// Register child theme view paths.
/*----------------------------------------------------*/
add_filter('themosisViewPaths', function($paths)
{
    $paths[] = get_stylesheet_directory().'app/views/';
    return $paths;
});
```
Then a define path and URLs to your child theme assets folder:
```php
/*----------------------------------------------------*/
// Register child theme asset paths.
/*----------------------------------------------------*/
add_filter('themosisAssetPaths', function($paths)
{
    $url = get_stylesheet_directory_uri().'app/assets'; // URL to your child theme assets directory

    $paths[$url] = get_stylesheet_directory().'app/assets';
    return $paths;
});
```
Those filters will add "locations" to search for assets and view files.

Also, because the framework don't use the default template files, I think your child theme should have the same file structure than the parent. At least an `index.php` and the `app/routes.php` files.

Haven't tested it but let me know if it fixes your issue.

**Comment by davidgeilfus** [comment]
Great, this works perfectly (I just needed to add a `/` before `app/views` and `app/assets`)… Many thanks!

**Comment by jlambe** [comment]
I'm also glad that it works ;)

**Comment by DannyvanHolten** [comment]
Is there an example anywhere how we can set up child themes in 1.3? I can't seem to get this working .. Maybe @davidgeilfus can shere it's child theme basics?
