### ISSUE TITLE
Creating Plugins

### ISSUE THREAD

**Issue by stanwarri** [themosis/themosis#46]
Hello,

This is not really an issue rather a request on how to create just a plugin using themosis. 

Thanks

**Comment by jlambe** [comment]
Hi,

you can hook into this to write custom code and use the framework classes for your plugin:

```php
add_action('themosis_bootstrap', function()
{
    // Bootstrap plugin code...
});
```

Currently you can't use the classes aliases on plugin development because the aliases are created on the theme (will change on a future release). So you have to use class full name. Here is an example on how to use the custom post type class:

```php
// Register a custom post type
\Themosis\Facades\PostType::make('my-post-type', 'Things', 'Thing')->set();
```

or you can import the classes at the top of your php file:

```php
<?php
use \Themosis\Facades\PostType;

PostType::make('my-post-type', 'Things', 'Thing')->set();
```

Check the theme `application.config.php` aliases property to get the list of classes with their full name: https://github.com/themosis/theme/blob/master/app/config/application.config.php

**Comment by stanwarri** [comment]
Thank you for the explanation. But it would be good to have a tutorial on your website on how to create a basic wordpress plugin using themosis

**Comment by jlambe** [comment]
Currently you can do it like any "classic" WordPress plugins. Just be sure to use the `themosis_bootstrap` hook. I'm not giving documentation at the moment as I intend to put a boilerplate plugin code in order to get started and enhance the API to develop plugins and themes with the framework. So you just have to be a little more patient ;)

But don't hesitate to ask anything if you encounter any issues during your plugin development.

**Comment by phredeye** [comment]
Has there been any progress on developing a boilerplate plugin?  

My employer creates dozens of wordpress sites, so we like to develop plugins for features that we use on multiple client sites.  Having the ability to reuse plugins across multiple themosis installs would be the lynch-pin in being able to sell this as the framework we standardize on as a company.

Even without documentation, any code, or basic pointers for a good folder structure, autoloading strategy, etc would be helpful.  

I really love this framework! Thanks for all the great work you've put in so far.

Any pointers?  Is there a dev repo I can follow?

**Comment by jlambe** [comment]
@phredeye I decided to target plugin development for release 1.3.0. But there is already some foundation in order to create plugin as "classic" php package and autoload everything. Check this repo for code example: https://github.com/ithinkdancan/framework

Sorry for the very late response, summer was quite busy ;)

**Comment by moise** [comment]
Hello Julien,
thank you very much for your super-work, I really really love your framework.
I was trying to use Themosis inside a custom plugin and following your example in the second post of this thread all worked great but now this no longer works, because, I think, the action 'themosis_bootstrap' no longer exist or no longer works :(
any alternative?
thank you!

**Comment by jlambe** [comment]
@moise Yes, it has been replaced by this hook: `themosis_bootstrap_plugins`. The callback also received a `Themosis\Core\Application` as an argument.

**Comment by moise** [comment]
I will try it, thank you @jlambe  ;)

**Comment by jlambe** [comment]
@moise You should also be able to use core classes with their shortname as aliases are now defined in core plugin. You can also overwrite them or add your own aliases thanks to this filter:
```php
add_filter('themosisClassAliases', function($aliases)
{
    $aliases['Your\\Namespace\\ClassName'] = 'ClassAlias';
    return $aliases;
});
```

**Comment by moise** [comment]
hummm seeems to not work:
this doesn't print anything
```php
add_action( 'themosis_bootstrap_plugins', function ( $path ) {
	error_log(var_export( 'hello world', true));
} );
```
my code is in a mu-plugin loaded after themosis

**Comment by jlambe** [comment]
@moise I answered too fast. In fact, the hook `themosis_boostrap_plugins` is already triggered when your plugin use it, so it won't work.

If you're using the framework as `mu-plugin`, you normally don't need to hook anything to develop your plugin now. Before release 1.2.0, the `themosis_boostrap` action was defined inside a `plugins_loaded` action hook which has the effect to delay the call.

So try removing any bootstrap hook and simply run your plugin, it should be working. Let me know how it goes.

**Comment by moise** [comment]
@jlambe I tried this in another project:
- Loaded Themosis Framework only as mu-plugin in a standard WordPress installation
- Created a custom mu-plugin and loaded it after Themosis by this

```php
require_once(WPMU_PLUGIN_DIR.'/themosis-framework/themosis.php');
require_once(WPMU_PLUGIN_DIR.'/custom-plugin/my-custom-plugin.php');
```
and added this line of code in my custom plugin:

```php
PostType::make( 'books', 'Books', 'Book' )->set( [ 'public' => true ] );
```
Unfortunately this make a died white page.
The same code placed in the theme's functions.php file it works great

any idea?

**Comment by jlambe** [comment]
@moise In fact after some development tests since your issue, I've developed a custom plugin for a client in order to test the plugin dev workflow with Themosis.

In fact, create a regular plugin and bootstrap your code on a `init` hook. Everything should work as expected.

If you need to configure some data and make it accessible before using the framework classes in your plugin, use the `plugins_loaded` hook.

On plugin development, the framework classes are only available on a `init` hook. Make sur to not call any of them before that hook. Only helper functions and filters are available before `init`.

**Comment by mithublue** [comment]
I already tried hooking the code in 'init', but works not okay.
require_once 'test-project/themosis.php';


add_action('init',function(){
    Metabox::make('Details', 'post')->set([
        Field::text('name'),
        Field::checkbox('channels', ['email', 'mail', 'morse'])
    ]);
});

The above code create meta box as expected , but not the fields inside that. Meaning a blank metabox is created.
There might be other issues with cases as well. Will you please find a correct solution for this?
I know, many out there are waiting and expecting it to be completely okay for plugin dev, cause it's a super excellent featureful framework ! Please, keep focus to make it suitable for plugin dev asap and you will see the real BOOM ! :) 
Thank you.

**Comment by jlambe** [comment]
Hi @mithublue,

did you install the framework by using the `themosis/themosis` package or simply install the `themosis/framework` as a plugin in a classic WordPress project?

Currently we've developed a custom plugin for a client using the framework and everything is working perfectly. We're using this project to future shape plugin development with Themosis as we know more people want this but plugin development needs more care than theme development. Be assure it's coming and if you can throw more code for your issue, I might be able to help you with this.

**Comment by mithublue** [comment]
I used themosis/framework.
To help a bit more clear about this, i submitted the code in this repo. will you please check it and make the changes to make it okay ?
thanks.
https://github.com/mithublue/test-plugin

**Comment by jlambe** [comment]
Why put the framework inside your own plugin?
Habitually I never work with a classic WordPress installation but I'll take a look and let you know.

**Comment by mithublue** [comment]
oh, how are you suggesting to integrate then, please?

**Comment by jlambe** [comment]
Just leave the themosis-framework as a separate plugin or better as a must-use plugin then only write your custom plugin using the `plugins_loaded` and `init` hooks.

**Comment by mithublue** [comment]
won't it work if i grab it and include it as dependency through 'composer require themosis/framework' command in a plugin ?

**Comment by jlambe** [comment]
In therory yes. But if you use composer why not use the framework structure which is optimized for composer use in place of a classic WordPress? It is best to keep the framework as an external dependency and refer to it than including it inside your plugin.

**Comment by mithublue** [comment]
i also tried the composer version, but the result was still the same ! :(

**Comment by moise** [comment]
Hello @jlambe after some days from my last post I tried what you suggest but does not work as expected.

What I need to do is simply make a custom post type from a mu-plugin instead of theme using Themosis classes.
As you said I made simple test function in the main plugin file and fired it on init hook.

```php
function myCustomTestFunction()
{
	PostType::make('books', 'Books', 'Book')->set([
		'public'    => true
	]);
}

add_action('init', 'myCustomTestFunction');
```
What is wrong?If what you said is right normally this should works or not?
Can you just test this in a mu plugin and, if it works, put your code here?

thank you very much
Moise

**Comment by jlambe** [comment]
In fact, your issue is a framework "bug". At least for APIs that already use the `init` hook.

The PostType and Taxonomy APIs both call the `init` hook at instantiation in order to register. So if you call the `PostType` or `Taxonomy` from a function hooked to a `init` hook, it is already too late. So get nothing in the wp-admin.

I encounter those issues on a client project last week and add those issues to the list. Both APIs need to be updated and check for the `current_filter()`. If we're already inside a hook callback, just register. If not, call the action and then register.

I'll try to provide the fix this week but if it's an emergency, update your framework `PostTypeBuilder` and `TaxonomyBuilder` classes to check the `current_filter()`.

**Comment by moise** [comment]
@jlambe thanks for your reply...I was happy to see my custom post type working good with plugins_loaded hook, but this broke the render view class: /themosis/htdocs/content/mu-plugins/themosis-framework/src/Themosis/View/ViewFinder.php on line 73
stack trace as attachment...hope can help you...
[stack-trace.txt](https://github.com/themosis/themosis/files/77036/stack-trace.txt)

**Comment by moise** [comment]
after some try it seems that all woks good with the after_setup_theme hook...

**Comment by jlambe** [comment]
When we developed one plugin, there were not so much issues but when you have several ones, there were conflicts with the theme using lower hooks than `init` but will test it more.

**Comment by moise** [comment]
I think your framework is very good an push developers to use WordPress in a modern and more efficient way...so hope our work (as tester :) ) can help you to improve it.

**Comment by jlambe** [comment]
@moise Thanks :)

I've update the themosis/framework plugin master branch with the PostType and Taxonomy APIs fixes. Update your project with latest master branch to test your plugin development.

**Comment by moise** [comment]
It works! thank you @jlambe :)

**Comment by jlambe** [comment]
@moise Great! Don't hesitate to post any issues you met during plugin development as it will help me shape a better plugin boilerplate package for development.

**Comment by stanwarri** [comment]
@jlambe Great work so far. I'm still waiting for a boilerplate plugin development package. I really want to start using this for plugin development

**Comment by jlambe** [comment]
This is still in development but in progress, stay tuned :+1:

**Comment by moazam1** [comment]
@jlambe any update on plugin boilerplate?

**Comment by jlambe** [comment]
It's coming with release 1.3.0 but nothing to show yet. But in the meantime you can still try or report any issues on the current 'dev' branch of the `themosis/framework` package. Search the Gitter channel for a list of currently modifier APIs and features:https://gitter.im/themosis/framework?at=57356bd68b845b284193eb3c

**Comment by jlambe** [comment]
Coming very soon...
