### ISSUE TITLE
Eloquent User Model to override Wordpress's Auth System.

### ISSUE THREAD

**Issue by devcflynn** [themosis/themosis#52]
So, I have Themosis in one folder, Laravel 5 in another. I want to share the User model between the two. I followed your post as mentioned here: http://t.co/RiPcgwaiyC I just can't see where I would override WP to look at my User model for Auth instead of the built in wp_users stuff, is this possible? The most ideal setup would be to setup Eloquent as mentioned in the post above and make the Users table configurable for WordPress. I'd love to hear your guy's thoughts on this as this could be a huge win for the Themosis framework as I have a feeling developers advocating the system will likely be leveraging Laravel or Symfony for the auth process. Plus it would make doing Single Sign On functionality a MASSIVE feature.

**Comment by jlambe** [comment]
Hi,
sorry for late response.
The main problem is that Laravel has a specific users table in the database and that their User model is tight closely to the framework.
The article is explaining how to load eloquent and set it up in order to use it with WordPress but I think you'll have to create your own User model for this.
