### ISSUE TITLE
How do page templates fit into Themosis

### ISSUE THREAD

**Issue by danieldunderfelt** [themosis/themosis#63]
Hi!

I'm very confused about the "page templates" in the context of Themosis. In vanilla Wordpress, they're separate PHP files that replace the `page.php` file when rendering pages. But in Themosis we can return whatever view we want for every route. Nonetheless the "page templates" feature is integrated into Themosis with its own config file and routing structure without being explained in the docs at all.

So what do I gain by defining page templates in the `templates.config.php` file? How can I make use of the template slug and the template title in my Themosis theme? What difference does it make when I assign page templates to Wordpress pages in the admin section? What do I use the template routes for?

I'm liking Themosis very much otherwise, but this one thing confuses me to no end. Thanks!

**Comment by jlambe** [comment]
Hi,

it is about template control. Currently the template feature mimics the WordPress one. One difference is that `Route::template` has always precedence over the `Route::page` or any other routes in fact. 

The following code will listen only to requests made to a page that has a template of `docs` associated with:
```php
// template.config.php
return [
    'docs' => 'Documentation'
];

// routes.php
Route::template('docs', function()
{
    // Return a view for pages that have the "docs" template.
    return View::make('pages.doc');
});
```
An other difference is that a `template` does not mean a single view necessarily. 

Also, I had to implement my own template because WordPress scans theme files one folder deep. So that means I had to let WordPress templates inside the `resources` directory. The WordPress does not allow to define a folder to look after template files plus I had no way to retrieve already parsed template file comments to get for example the name of the template.

Then there is the idea (not yet implemented) to allow templates to other custom post types, so the `templates.config.php` file makes it possible as we have total control of it.

**Comment by danieldunderfelt** [comment]
Okay thanks, that made it clearer!

**Comment by BenceSzalai** [comment]
Is `Route::template(` a custom macro or is it a built in method that was part of Themosis, but has been removed since?
I've found `Route::template('docs', function()...` can be replaced with `Route::get( 'template', ['docs',function()...`, but wondering where the method mentioned above is coming from, as it seems not to be available in Themosis v2.

**Comment by jlambe** [comment]
@BenceSzalai The `Route::template` was a method available in version 1.+ of the framework. Since version 2, you have to use the `Route::get('template', ...)` method.

The old one has been removed.
