### ISSUE TITLE
Renaming htdocs to public like Laravel

### ISSUE THREAD

**Issue by mariusvw** [themosis/themosis#65]
I am wondering, could it be possible to rename the htdocs folder to public like Larvel by default?

**Comment by moise** [comment]
In my experience renaming the htdocs broke the framework...I think it should be parameterized with a env param because not all hosting providers allow you to set a custom root folder.

**Comment by jlambe** [comment]
Hi, in fact you can but you need to do some work:
- Rename your `htdocs` folder of course...
- Update the `$webRoot` variable inside the `bootstrap/start.php` file to reflect that change.
- Then update the `composer.json` file and replace all `htdocs` references inside the `require` and or `require-dev` sections.
- Run `composer update` in your terminal or console in order to update the composer `autoload` files.

**Comment by mariusvw** [comment]
For now we symlink the public to htdocs to get it working or indeed change all paths.

What I came across for the root folder names are:
- public (most common for Laravel)
- webroot
- secure_html
- private_html
- public_html
- htdocs
- www
- privdocs
- pubdocs

I prefer the public directory due the Laravel default.
I use Laravel and Themosis thats why I request if it could be changed by default.

**Comment by jlambe** [comment]
I still think it will be hard to provide a parameter to easily change the `htdocs` folder as like you mentioned, there is a large variety of names per hosting provider. As an agency, I suppose you will adapt your project based on your provider.

If you need to always use the `public` directory, I suggest you to fork the `themosis/themosis` repository, make your changes and then when you want to start a project for your company simply use the composer `create-project` to use your repository like so:

```bash
composer create-project mycompany/themosis myProject
```

**Comment by mariusvw** [comment]
I understand how you can change it, it was more a suggestion of preference due the default public directory in Laravel. If you use both Themosis and Laravel it is of nice to have them both with the same root directory :)

**Comment by Joe5** [comment]
@jlambe Is it possible to completely remove htdocs dir? I've tried what you have suggested with updating `$webRoot` and `composer update` however it looks like the files are not completely autoloaded.

I am getting this error:
`Fatal error: Call to undefined function themosis_set_paths() in { projectRoot } /content/themes/themosis-theme/functions.php on line 159`

It looks like that `vendor/autoload.php` is loaded and the site is working correctly until I activate my `themosis-theme`.


What I want to do is make sure that I can install my application on restrictive hosting that my client has already paid for and does not want to change it. The hosting where I am not allowed to use SSH or to change root folder.

**Comment by Joe5** [comment]
You could just make .htaccess rewrite like this:
```
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteRule ^(.*)$ htdocs/$1 [L]
</IfModule>
```
It would silently redirect traffic from root to subdirectory. But of course only if your have hosting provider allows you to use .htaccess settings and of course mod rewrite.

**Comment by mariusvw** [comment]
@Joe5 .htaccess Nginx hosting won't support that... For now I symlink htdocs to get it working.

**Comment by jlambe** [comment]
I wonder how you package Themosis with Laravel? Personnaly, I would grab the illuminate packages and simply load them accordingly with composer. If you install Laravel and put Themosis to use the same public directory, there would be route conflicts. How predict which "framework" will listen to the user request?

**Comment by Joe5** [comment]
@mariusvw Well I didn't knew that and also I did not knew you were using Nginx. I just assumed the most popular...

@jlambe I think he does not mean at the same time but instead that he uses Laravel for some, more specific or bigger projects and WordPress with Themosis for other projects. In my opinion he just wants to have some consistency in projects or their setup.

I think that it would be nice if we could use Themosis with default WordPress structure. Compatibility is one of the main reasons why we choose WordPress in the first place. The whole point of public directory is that your code is not publicly accessible because it's outside of the document root. We loose this benefit since we have our code inside themes directory. It use to be trivial * to use it with default WordPress structure but now it's a bit more complicated. 

But I also think that Themosis should not be going through such drastic changes often. Backwards compatibility of the framework should be one of the top priorities. Staying up to date with all the changes in a framework is one of the most painful things of using one in the first place.

* Check this video for more info: https://www.youtube.com/watch?v=7wqpr6S8b5I

PS: Sorry for my bad English, it's not my native language.

**Comment by mariusvw** [comment]
> In my opinion he just wants to have some consistency in projects or their setup.

Thats exactly why I requested it :)

Hosting does not always provide changing the document root but having it named the same for laravel / lumen / wordpress / themosis is kind of more easy to work with.

It is not really a problem thats why my question was more something I was wondering about :)

**Comment by jlambe** [comment]
Ahhhhhhhh ok :smiley:  Now I understand your issue... But definitely it's hard to choose one folder name that fits for everyone.

Nonetheless, perhaps something we could look at, is to make a CLI command to create a new project where we ask the user to define the name of the public directory and the CLI tool builds it accordingly or rename it. Also, in order to stay consistent with the WordPress project, look to integrate this with WP-CLI. Is there anyone familiar with building CLI commands and tools?

**Comment by Joe5** [comment]
Unfortunately I don't, at most I did some very simple bash scripts or simple gulp functions.

Anyway why don't you just define some config variables for it and dynamically construct that path in application? I don't think that it should be huge performance hit for the application.

**Comment by pryley** [comment]
Here is a [custom Laravel Valet driver](https://laravel.com/docs/master/valet#custom-valet-drivers) for Themosis:

```php
<?php

class ThemosisValetDriver extends BasicValetDriver
{
    public function serves( $sitePath, $siteName, $uri )
    {
        return file_exists( $sitePath.'/htdocs/wp-config.php' );
    }

    public function isStaticFile( $sitePath, $siteName, $uri )
    {
        if( $this->isActualFile( $staticFilePath = $sitePath.'/htdocs'.$uri )) {
            return $staticFilePath;
        }
        return false;
    }

    public function frontControllerPath( $sitePath, $siteName, $uri )
    {
        $_SERVER['PHP_SELF'] = $uri;
        if( strpos( $uri, '/cms/' ) === 0 ) {
            return is_dir( $sitePath.'/htdocs'.$uri )
                ? $sitePath.'/htdocs'.$this->forceTrailingSlash( $uri ).'/index.php'
                : $sitePath.'/htdocs'.$uri;
        }
        return $sitePath.'/htdocs/index.php';
    }

    private function forceTrailingSlash($uri)
    {
        if( substr( $uri, -1 * strlen( '/cms/wp-admin' )) == '/cms/wp-admin' ) {
            header( 'Location: '.$uri.'/' );
            die;
        }
        return $uri;
    }
}
```

**Comment by graphixar** [comment]
how to change wp language in themosis? i need fa_ir
