### ISSUE TITLE
[Installation problem] Selecting french lang

### ISSUE THREAD

**Issue by jessy-barthelemy** [themosis/themosis#68]
Hello I can't install themosis in Fr. When I try to do it I have this error :
![error](https://cloud.githubusercontent.com/assets/15871134/12913175/61cb3ff6-cf1d-11e5-9fbe-9dda9bb94472.jpg)

But i can install my themosis in english and change the lang after and it works.

**Comment by jlambe** [comment]
Hi,
this is a core WordPress bug which is resolved and should come with WordPress 4.5.
In the meantime, before installing, change your local environment settings to not display all errors. In order to do so, open the `config/environments/local.php` file, and set the constant `THEMOSIS_ERROR_REPORT` to a value of `0`. 
Make your installation and then reset the value to `-1` in order to develop.

**Comment by jessy-barthelemy** [comment]
OK thanks :)
