### ISSUE TITLE
Scripts not loaded in footer

### ISSUE THREAD

**Issue by moise** [themosis/themosis#78]
Hello @jlambe,
I have an issue on trying to load a js file in footer.
Simply added this line of code in the application.php file:

```PHP
Asset::add('alpine-rescue',  'js/alpine-rescue.min.js', [ 'jquery' ], '1.0', true);
```
It works well if the script is loaded on the header (omitting the last parameter or turned it to false)...

another strange issue is that this assets is loaded on the footer O.o
```PHP
Asset::add('open-sans', 'http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all', false, '1.0', 'all');
```

sorry but I can't understand where the issue could be...any idea?
thank you in advance

**Comment by jlambe** [comment]
For the first asset statement it is strange indeed as your code is correct. Which version of the framework do you use?

Regarding the second one, it's normal because by default the method, if the asset cannot be recognized, it is handled as a script. Now it's weird that it loads in footer.
You can force the type of the asset like so:
```php
Asset::add('open-sans', 'http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all', false, '1.0', 'all', 'style');
```
Add the 5th parameter to force the type. `style` or `script`.

**Comment by moise** [comment]
Hello,
unfortunately forcing the type doesn't change anything...the font is always loaded in footer and the scripts is not loaded at all...I'm working with the latest version of the framework...I'll try to do some debug...
