### ISSUE TITLE
After Upgrade (WP 4.5): Fatal error: Call to undefined function add_filter() ..bootstrap/start.php

### ISSUE THREAD

**Issue by maximusblade** [themosis/themosis#85]
I am getting the following error after upgrading to 1.2.3
Fatal error: Call to undefined function add_filter() ..... bootstrap/start.php on line 7

Is there something I may have missed?
I followed the upgrade guide 
http://framework.themosis.com/docs/upgrade-guide/

**Comment by jlambe** [comment]
That's weird, it would means WordPress is not loaded. So you were running WordPres 4.4 with the framework version 1.2.0 then updating everything?

**Comment by maximusblade** [comment]
Yes I believe that is what happened


  - Removing johnpbloch/wordpress (4.4.2)
  - Installing johnpbloch/wordpress (4.5)
    Downloading: 100%

  - Removing themosis/framework (1.2.2)
  - Installing themosis/framework (1.2.3)
    Downloading: 100%

**Comment by jlambe** [comment]
The error is triggered from your theme's bootstrap file and at that moment the framework is loaded as a plugin but none of its classes is already used when loading the `start.php` file. The error you get means WordPress is not loaded for me, so the `add_filter()` function is not yet defined.

I have tested WordPress 4.5 with framework 1.2.3 and it's working fine. Can you try installing a fresh installation and simply move your theme into it and see how it goes?

**Comment by mundgold** [comment]
I am getting exact the same error after the update in dokumented order. Fatal error: Call to undefined function add_filter() in /....../bootstrap/start.php on line 7

**Comment by jlambe** [comment]
Can you provide a copy of your entire project before update for testing perhaps so I can check what's going on?

**Comment by mundgold** [comment]
ok I installed a fresh installation and moved my theme - then made changes in accordance with upgrade-Guide (aliases in application.config.php) - After that I had to place all widgets in the sidebars because they disappeared ... 

and one thing doesn't work after upgrade from 1.2.2 to 1.2.3 - and I have no idea why:
In my routes.php I use this:

Route::any('page', ['buchinfo', 'uses' => 'PagesController@buchinfo']);

in my "admin/actions.php"  I have this:

/**
 * add rewrite tag isbn
 */
add_action('init', function ()
{
    add_rewrite_tag('%isbn%', '([^&]+)');
}, 10, 0);

/**
 * add rewrite rule for param isbn on buchinfo page (pageid 1086)
 */
add_action('init', function ()
{
    add_rewrite_rule('^buchinfo/([^/]*)/?', 'index.php?page_id=1086&isbn=$matches[1]', 'top');
}, 10, 0);

on request -> http://domainname.com/buchinfo/9783442479108

I get no value for $query->query_vars['isbn'] in my "buchinfo-Method"

the request on http://domainname.com/index.php?page_id=1086&isbn=9783442479108

works as expected.

In themosis 1.2.2 and WP 4.5 it works.

Have you any idea on this issue?

Thanks a lot
Roland

**Comment by jlambe** [comment]
Did you visit the permalink page to flush the rewrite rules? or run the flush_rewrite_rules() function? This is necessary when defining custom rewrite rules in order to make them work.

**Comment by mundgold** [comment]
oh my good - thanks a lot for your fast reply!!

... I did that last time to - after I searched like today for a solution - and now I forot it again :-|

Have a nice evening :-)

**Comment by jlambe** [comment]
Any feedback regarding your issue? Is everything solved?

**Comment by mundgold** [comment]
After upgrade failed with: Fatal error: Call to undefined function add_filter() in /....../bootstrap/start.php on line 7 I followed your recommendation for an new installation and to add my theme.

I have done this in my testing environment - I am a little nervous to deploy the project to production - I only upgraded wp to 4.5 in production environment in the backend of wordpress and not the composer-way.

By the way is it an appropriate action to upgrade themosis via composer and wordpress in the backend by click on the upgrade-button - because the language support is easier that way?

**Comment by jlambe** [comment]
If you have total control of the project, it is better to update WordPress doing a `composer update`. Because you define the WordPress version and you'll know it's going to work with that precise version. Doing from the UI, you're loosing track of the versioning.

Then regarding language support, once WordPress is updated, simply visit the Update screen to update translations as these are outside WordPress core and are not considered code-breaker files.
