### ISSUE TITLE
Moving project to another pc ( Homestead, bitBucket )

### ISSUE THREAD

**Issue by naknak12** [themosis/themosis#91]
Hello, I have trouble with moving an installation of themosis + wordpress to another pc. I get this error:
![4e510ea8-d9c0-496e-8f66-4eb49de7c493](https://cloud.githubusercontent.com/assets/15021710/15436962/9d67da64-1ec4-11e6-8af7-5b347e1d5453.jpg)

If i type 'composer install' the error is gone, but if i go to themes i see there a double themosis-theme installation.

**Comment by jlambe** [comment]
Hi,
the theme acts as a boilerplate. So everytime you start a new project, you should always rename the `themosis-theme` folder to a name that represents your project.
Because each time you'll run `composer install` or `composer update`, it normally erases your current `themosis-theme`.
Usually, I delete the requirement to the `themosis-theme` after installation.
Each time you move your project, you always have to re-download the dependencies as the `vendor` directory is ignored on git source control, including autoloading classes which is what the error message above are.

**Comment by naknak12** [comment]
Thanks, it worked but i also had to move the storage folder back with the views in it. It is ignored by pushing the project to bitbucket.

**Comment by jlambe** [comment]
Yes, I'm aware of this gitignore issue for the storage views. It should be fixed on next release.
