### ISSUE TITLE
Customize html markup for user fields

### ISSUE THREAD

**Issue by Cezarion** [themosis/themosis#93]
Hello, 

On my project, user can edit their data outside the administration interface.
I hadded custom user fields with addSection and addFields.
Now, I would like to customize the html markup (remove table, ... ) but I don't understand how I can do it. 
I have read the Metabox section on the website but I don't know if this : 
`$view = View::make('metabox.custom');

Metabox::make('Properties', 'user', ['priority' => 'high'], $view);`

wil works.

Thank's for your help

**Comment by jlambe** [comment]
This is working in order to define your metabox custom view, but it won't automatically loads the custom fields attached to that metabox. For this, you need to add extra code/markup. Check the `_themosisCoreMetabox.scout.php` file for a code sample: https://github.com/themosis/framework/blob/master/src/Themosis/Metabox/Views/_themosisCoreMetabox.scout.php

All custom fields are passed to your metabox custom view under the variable `$__fields`. It's an array of Field instances. Create your markup and loop through them in order to display them. But you need to use a `<table></table>`  in order to properly render them as each field core view is uses `<tr>` and `<td>` tags. Perhaps I should change that on future version with divs so it's more flexible on customization.

Hope this helps and sorry for only responding now. Cheers,
