### ISSUE TITLE
Using Wordpress Theme

### ISSUE THREAD

**Issue by heikobihlmaier** [themosis/themosis#95]
Hello,

I buy a normal wordpress theme within ThemeForest. How can I make this to work with Themosis Framework ? Is that possible or not ?  The structure is very different.

Thanks for your help.

Greetings.

**Comment by jlambe** [comment]
Yes, just install it as usual, it will work as expected. The theme is not a hard dependency, it's just boilerplate with suggested code structure. So you're good to go ;)

**Comment by heikobihlmaier** [comment]
And how I can overwrite theme template files ? Can I use route file and MVC Structure as normal ?

**Comment by jlambe** [comment]
You can work with the routes.php file, I suggest you to explore the `bootstrap/start.php` file from the Themosis theme in order to configure your theme. Basically there are filters in order to register your asset folder, views directory, and the code the use composer autoloading feature for your theme classes.

Put those configurations first inside your actual theme `functions.php` file and then you're good to go.

You're not force to use a routes.php file. You can simply use your theme template files and call your views directly from each template.

For example, if you have a `home.php` template, you write this code below (with a views directory registered):
```php
// Inside home.php
echo Themosis\Facades\View::make('pages.home', ['key' => 'value'])->render();
```
This code will output your `home.scout.php` view file from your `views/pages` directory.

**Comment by heikobihlmaier** [comment]
Okay. But I need to rewrite all theme templates to view is that correct ? Otherwise i need to overwrite in theme as normal. Can I combine both?

**Comment by jlambe** [comment]
Sure you can combine both. A view is simply some string so you can have your exsting template and simply write a section with a view and render it inside the template. The theme is working as usual, if you don'y use the APIs, nothin wrong is going to happen. For example, you can install the framework, add the tweety sixteen theme and everything is going to work as expected.

**Comment by heikobihlmaier** [comment]
But I can't extend the wordpress layout into my view ? When I need to this, I need to change all to views correct ?

**Comment by jlambe** [comment]
Default templates are written in php only. In order to use layouts, you need to use the `scout` template engine with your views. Now perhaps a code sample of what you're trying to achieve may be easier to tell.

**Comment by heikobihlmaier** [comment]
Okay I try to explain:

My customer has buy this theme: http://themeforest.net/item/porto-responsive-wordpress-woocommerce-theme/9207399

Now I need to make 2 extensions for wordpress and I need to overwrite some templates of this theme.
For these actions I want to use themosis. 

But I don't know, how I can use the exist templates of the theme.

Do u know what I mean ?

**Comment by heikobihlmaier** [comment]
http://laravel.io/bin/1ymlw

This is the index.php 

Here I need to include my extension...

**Comment by jlambe** [comment]
You could copy/paste existing code into a custom view with the `scout` extension. Inside the current template file, use the `echo Themosis\Facades\View::make('custom')->render();` And then work into your view file to extend it.
